In [45]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sweetviz as sv
pd.set_option("display.max_columns", None)  # Show all columns
pd.set_option("display.width", 1000)
pd.set_option('display.float_format', '{:.3f}'.format)

## Labour Force Survey

#### Data Loading

In [46]:
## Set the working directory to the script's location
os.chdir('/Users/joudisinjab/Documents/GitHub/capstone_project')

## Listing all CSV file paths
csv_files = [
'Data/LFS/pub0920.csv', 'Data/LFS/pub1020.csv', 'Data/LFS/pub1120.csv', 'Data/LFS/pub1220.csv',
'Data/LFS/pub0121.csv', 'Data/LFS/pub0221.csv', 'Data/LFS/pub0321.csv', 'Data/LFS/pub0421.csv',
'Data/LFS/pub0521.csv', 'Data/LFS/pub0621.csv', 'Data/LFS/pub0721.csv', 'Data/LFS/pub0821.csv',
'Data/LFS/pub0921.csv', 'Data/LFS/pub1021.csv', 'Data/LFS/pub1121.csv', 'Data/LFS/pub1221.csv',
'Data/LFS/pub0122.csv', 'Data/LFS/pub0222.csv', 'Data/LFS/pub0322.csv', 'Data/LFS/pub0422.csv',
'Data/LFS/pub0522.csv', 'Data/LFS/pub0622.csv', 'Data/LFS/pub0722.csv', 'Data/LFS/pub0822.csv',
'Data/LFS/pub0922.csv', 'Data/LFS/pub1022.csv', 'Data/LFS/pub1122.csv', 'Data/LFS/pub1222.csv',
'Data/LFS/pub0123.csv', 'Data/LFS/pub0223.csv', 'Data/LFS/pub0323.csv', 'Data/LFS/pub0423.csv',
'Data/LFS/pub0523.csv', 'Data/LFS/pub0623.csv', 'Data/LFS/pub0723.csv', 'Data/LFS/pub0823.csv',
'Data/LFS/pub0923.csv', 'Data/LFS/pub1023.csv', 'Data/LFS/pub1123.csv', 'Data/LFS/pub1223.csv',
'Data/LFS/pub0124.csv', 'Data/LFS/pub0224.csv', 'Data/LFS/pub0324.csv', 'Data/LFS/pub0424.csv',
'Data/LFS/pub0524.csv', 'Data/LFS/pub0624.csv', 'Data/LFS/pub0724.csv', 'Data/LFS/pub0824.csv',
'Data/LFS/pub0924.csv', 'Data/LFS/pub1024.csv', 'Data/LFS/pub1124.csv', 'Data/LFS/pub1224.csv',
'Data/LFS/pub0125.csv', 'Data/LFS/pub0225.csv']

## Load all CSVs into a list of DataFrames
dfs = [pd.read_csv(file) for file in csv_files]
  
## Concatenate them into one DataFrame
LFS = pd.concat(dfs, ignore_index=True)
print(f"There are {LFS.shape[0]} rows, and {LFS.shape[1]} columns in the LFS dataset")

## Checking data for duplicates
print(f"There are {LFS.duplicated().sum()} duplicates in LFS\n")

There are 5507987 rows, and 60 columns in the LFS dataset
There are 0 duplicates in LFS

In [47]:
## Printing summary information
print("====================Information about LFS dataset====================")
print(LFS.info())

## Printing summary statistics
print("====================Summary information about LFS dataset====================")
LFS.describe()

====================Information about LFS dataset====================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5507987 entries, 0 to 5507986
Data columns (total 60 columns):
 #   Column    Dtype
---  ------    -----
 0   REC_NUM   int64
 1   SURVYEAR  int64
 2   SURVMNTH  int64
 3   LFSSTAT   int64
 4   PROV      int64
 5   CMA       int64
 6   AGE_12    int64
 7   AGE_6     float64
 8   GENDER    int64
 9   MARSTAT   int64
 10  EDUC      int64
 11  MJH       float64
 12  EVERWORK  float64
 13  FTPTLAST  float64
 14  COWMAIN   float64
 15  IMMIG     int64
 16  NAICS_21  float64
 17  NOC_10    float64
 18  NOC_43    float64
 19  YABSENT   float64
 20  WKSAWAY   float64
 21  PAYAWAY   float64
 22  UHRSMAIN  float64
 23  AHRSMAIN  float64
 24  FTPTMAIN  float64
 25  UTOTHRS   float64
 26  ATOTHRS   float64
 27  HRSAWAY   float64
 28  YAWAY     float64
 29  PAIDOT    float64
 30  UNPAIDOT  float64
 31  XTRAHRS   float64
 32  WHYPT     float64
 33  TENURE    float64
 34  PREVTEN   float64
 35  HRLYEARN  float64
 36  UNION     float64
 37  PERMTEMP  float64
 38  ESTSIZE   float64
 39  FIRMSIZE  float64
 40  DURUNEMP  float64
 41  FLOWUNEM  float64
 42  UNEMFTPT  float64
 43  WHYLEFTO  float64
 44  WHYLEFTN  float64
 45  DURJLESS  float64
 46  AVAILABL  float64
 47  LKPUBAG   float64
 48  LKEMPLOY  float64
 49  LKRELS    float64
 50  LKATADS   float64
 51  LKANSADS  float64
 52  LKOTHERN  float64
 53  PRIORACT  float64
 54  YNOLOOK   float64
 55  TLOLOOK   float64
 56  SCHOOLN   float64
 57  EFAMTYPE  int64
 58  AGYOWNK   float64
 59  FINALWT   int64
dtypes: float64(47), int64(13)
memory usage: 2.5 GB
None
====================Summary information about LFS dataset====================

          REC_NUM    SURVYEAR    SURVMNTH     LFSSTAT        PROV         CMA      AGE_12       AGE_6      GENDER     MARSTAT        EDUC         MJH    EVERWORK   FTPTLAST     COWMAIN       IMMIG    NAICS_21      NOC_10      NOC_43    YABSENT    WKSAWAY    PAYAWAY    UHRSMAIN    AHRSMAIN    FTPTMAIN     UTOTHRS     ATOTHRS     HRSAWAY      YAWAY      PAIDOT    UNPAIDOT     XTRAHRS      WHYPT      TENURE    PREVTEN    HRLYEARN       UNION    PERMTEMP     ESTSIZE    FIRMSIZE   DURUNEMP   FLOWUNEM   UNEMFTPT   WHYLEFTO   WHYLEFTN    DURJLESS   AVAILABL   LKPUBAG  LKEMPLOY    LKRELS    LKATADS  LKANSADS  LKOTHERN   PRIORACT   YNOLOOK   TLOLOOK     SCHOOLN    EFAMTYPE     AGYOWNK     FINALWT
count 5507987.000 5507987.000 5507987.000 5507987.000 5507987.000 5507987.000 5507987.000 1041102.000 5507987.000 5507987.000 5507987.000 3217830.000 2290157.000 371814.000 3589644.000 5507987.000 3589644.000 3589644.000 3589644.000 298279.000 298279.000 267036.000 3217830.000 3217830.000 3217830.000 3217830.000 3217830.000 2519720.000 423501.000 2519720.000 2519720.000 2519720.000 590710.000 3217830.000 371814.000 2769600.000 2769600.000 2769600.000 2769600.000 2769600.000 198400.000 208631.000 208631.000 371814.000 371814.000 1943232.000 232369.000 22803.000 89875.000 60767.000 144369.000 80427.000 44856.000 186304.000 73331.000 12096.000 4082914.000 5507987.000 1423889.000 5507987.000
mean    51574.341    2022.524       6.588       2.264      34.649       1.691       7.328       3.580       1.514       2.822       3.405       1.055       1.989      1.338       2.138       2.734      13.105       5.246      23.126      1.746     13.946      1.534     358.389     320.540       1.184     366.157     327.411      17.980      2.151       8.637       6.537      15.173      4.110      96.144     64.055    3234.573       2.355       1.246       2.191       2.980     17.654      4.402      1.361      3.356      7.702     109.101      1.943     1.000     1.000     1.000      1.000     1.000     1.000      1.514     2.409     1.707       1.141       6.276       2.205     317.559
std     30377.710       1.316       3.574       1.418      14.636       2.768       3.572       1.734       0.500       2.155       1.628       0.227       0.560      0.473       1.216       0.557       5.105       2.652      12.698      1.127     21.842      0.499     118.136     163.791       0.387     123.566     168.202      50.596      1.054      36.594      29.113      46.148      1.841      85.037     83.279    1741.215       0.924       0.715       1.042       1.171     21.325      2.150      0.573      1.425      3.421      89.060      0.231     0.000     0.000     0.000      0.000     0.000     0.000      0.959     1.969     0.455       0.398       5.377       1.089     302.611
min         1.000    2020.000       1.000       1.000      10.000       0.000       1.000       1.000       1.000       1.000       0.000       1.000       1.000      1.000       1.000       1.000       1.000       1.000       1.000      0.000      1.000      1.000       1.000       0.000       1.000       1.000       0.000       0.000      0.000       0.000       0.000       0.000      0.000       1.000      1.000     321.000       1.000       1.000       1.000       1.000      1.000      1.000      1.000      0.000      0.000       1.000      1.000     1.000     1.000     1.000      1.000     1.000     1.000      0.000     0.000     1.000       1.000       1.000       1.000       1.000
25%     25500.000    2021.000       3.000       1.000      24.000       0.000       4.000       2.000       1.000       1.000       2.000       1.000       2.000      1.000       2.000       3.000      10.000       3.000      11.000      1.000      1.000      1.000     325.000     240.000       1.000     350.000     240.000       0.000      1.000       0.000       0.000       0.000      3.000      20.000      5.000    2000.000       1.000       1.000       1.000       2.000      4.000      2.000      1.000      3.000      5.000      23.000      2.000     1.000     1.000     1.000      1.000     1.000     1.000      1.000     1.000     1.000       1.000       2.000       1.000     130.000
50%     51000.000    2023.000       7.000       1.000      35.000       0.000       8.000       4.000       2.000       2.000       4.000       1.000       2.000      1.000       2.000       3.000      14.000       5.000      25.000      2.000      3.000      2.000     400.000     375.000       1.000     400.000     375.000       0.000      3.000       0.000       0.000       0.000      4.000      66.000     20.000    2780.000       3.000       1.000       2.000       3.000      8.000      5.000      1.000      4.000      9.000      89.000      2.000     1.000     1.000     1.000      1.000     1.000     1.000      1.000     2.000     2.000       1.000       4.000       2.000     210.000
75%     76500.000    2024.000      10.000       4.000      47.000       3.000      11.000       5.000       2.000       6.000       5.000       1.000       2.000      2.000       2.000       3.000      17.000       7.000      34.000      3.000     17.000      2.000     400.000     400.000       1.000     400.000     400.000       0.000      3.000       0.000       0.000       0.000      5.000     169.000     92.000    4019.000       3.000       1.000       3.000       4.000     24.000      6.000      2.000      4.000     10.000     200.000      2.000     1.000     1.000     1.000      1.000     1.000     1.000      2.000     4.000     2.000       1.000      11.000       3.000     376.000
max    113780.000    2025.000      12.000       4.000      59.000       9.000      12.000       6.000       2.000       6.000       6.000       2.000       3.000      2.000       7.000       3.000      21.000      10.000      43.000      3.000     99.000      2.000     990.000     990.000       2.000     990.000     990.000     990.000      4.000     990.000     990.000     990.000      7.000     240.000    240.000   23590.000       3.000       4.000       4.000       4.000     99.000      8.000      3.000      5.000     13.000     240.000      2.000     1.000     1.000     1.000      1.000     1.000     1.000      3.000     6.000     2.000       3.000      18.000       4.000    6526.000

#### Data cleaning

In [48]:
## Renaming columns for clarity 
LFS = LFS.rename(columns={'SURVYEAR' : 'survey_year', 'SURVMNTH' : 'survey_month', 'LFSSTAT' : 'lf_status', 'PROV' : 'province', 'CMA' : 'cmetrop_area', 'AGE_12' : 'age_5y_group', 'AGE_6' : '2_3y_age', 
                          'GENDER' : 'gender', 'MARSTAT' : 'marital_stat', 'EDUC' : 'education', 'MJH' : 'multiple_jobh', 'EVERWORK' : 'work_lasty', 'FTPTlast' : 'ft_pt_last', 
                          'COWMAIN' : 'main_class_worker', 'IMMIG' : 'immigration_stat', 'YABSENT' : 'rsn_absent_fullwk', 'WKSAWAY' : 'weeks_absent', 'PAYAWAY' : 'paid_for_absence', 
                          'UHRSMAIN': 'usualhrs_main', 'AHRSMAIN' : 'actualhrs_main', 'FTPTMAIN' : 'ft_pt_main', 'UTOTHRS' : 'usualhrs_all', 'ATOTHRS' : 'actualhrs_all',
                          'HRSAWAY' : 'hrs_away', 'YAWAY' : 'rsn_away', 'PAIDOT' : 'paid_overtime', 'UNPAIDOT' : 'unpaid_overtime', 'XTRAHRS' : 'hrs_overtime', 
                          'WHYPT' : 'rsn_pt', 'TENURE' : 'current_tenure', 'PREVTEN' : 'prev_tenure', 'HRLYEARN' : 'hourly_wage', 'UNION' : 'union_stat', 
                          'PERMTEMP' : 'job_permenancy', 'ESTSIZE' : 'estab_size', 'FIRMSIZE' : 'firm_size', 'DURUNEMP' : 'duration_unemp', 
                          'FLOWUNEM' : 'flow_to_unemp', 'UNEMFTPT' : 'job_seekers_temp_layoffs_status', 'WHYLEFTO' : 'rsn_left_old', 
                          'WHYLEFTN' : 'rsn_left_new', 'DURJLESS' : 'duration_jobless', 'AVAILABL' : 'availability', 'LKEMPLOY' : 'unemp_checked_employers',
                          'LKPUBAG' : 'unemp_public_agency', 'LKRELS' : 'unemp_checked_friends', 'LKATADS' : 'unemp_job_ads', 'LKANSADS' : 'unemp_answered_ads',
                          'LKOTHERN' : 'unemp_other_methods', 'PRIORACT' : 'prior_activity', 'YNOLOOK' : 'rsn_not_looking', 'TLOLOOK' : 'temp_layoff_looked', 
                          'SCHOOLN' : 'student_status', 'EFAMTYPE' : 'econ_fam_type', 'AGYOWNK' : 'age_youngest', 'FINALWT' : 'final_wt', 'FTPTLAST' : 'ft_pt_last'})

##### The following columns were removed due to high missingness or limited relevance in this study's scope.

In [49]:
## Dropping highly null columns and unrelevant columns to analysis
col_to_drop = ['cmetrop_area', '2_3y_age', 'rsn_absent_fullwk', 'rsn_away', 'rsn_pt',  'age_youngest', 'unemp_public_agency', 'unemp_checked_employers', 'unemp_checked_friends', 'unemp_job_ads', 'unemp_answered_ads', 
                'unemp_other_methods', 'rsn_not_looking', 'job_seekers_temp_layoffs_status', 'rsn_left_old', 'rsn_left_new', 'temp_layoff_looked', 'prior_activity', 'availability']

for col in col_to_drop:
    LFS.drop(columns=[col], inplace=True)
    print(f"{col} has been dropped from LFS dataframe.")

cmetrop_area has been dropped from LFS dataframe.
2_3y_age has been dropped from LFS dataframe.
rsn_absent_fullwk has been dropped from LFS dataframe.
rsn_away has been dropped from LFS dataframe.
rsn_pt has been dropped from LFS dataframe.
age_youngest has been dropped from LFS dataframe.
unemp_public_agency has been dropped from LFS dataframe.
unemp_checked_employers has been dropped from LFS dataframe.
unemp_checked_friends has been dropped from LFS dataframe.
unemp_job_ads has been dropped from LFS dataframe.
unemp_answered_ads has been dropped from LFS dataframe.
unemp_other_methods has been dropped from LFS dataframe.
rsn_not_looking has been dropped from LFS dataframe.
job_seekers_temp_layoffs_status has been dropped from LFS dataframe.
rsn_left_old has been dropped from LFS dataframe.
rsn_left_new has been dropped from LFS dataframe.
temp_layoff_looked has been dropped from LFS dataframe.
prior_activity has been dropped from LFS dataframe.
availability has been dropped from LFS dataframe.

In [50]:
## Formatting Dates columns
month_order = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

LFS['REF_DATE'] = LFS['survey_year'].astype(str) + "-" + LFS['survey_month'].astype(str).str.zfill(2)
LFS['REF_DATE'] = pd.to_datetime(LFS['REF_DATE'], format='%Y-%m')

LFS['Month'] = LFS['REF_DATE'].dt.strftime('%b')
LFS['Month'] = pd.Categorical(LFS['Month'], categories=month_order, ordered=True)
LFS['REF_DATE'] = LFS['REF_DATE'].dt.date

## Sorting the data by month
LFS = LFS.sort_values('Month')
LFS.drop(columns=['survey_year', 'survey_month'], inplace=True)

In [51]:
## Formatting numerical columns

## Data documentation states that two decimal spaces are implied, changing the format to show true hourly wage
LFS['hourly_wage'] = LFS['hourly_wage']/100

## Data documentation states that one decimal space is implied
LFS['usualhrs_main'] = LFS['usualhrs_main'] / 10
LFS['actualhrs_main'] = LFS['actualhrs_main'] / 10
LFS['usualhrs_all'] = LFS['usualhrs_all'] / 10
LFS['actualhrs_all'] = LFS['actualhrs_all'] / 10
LFS['hrs_away'] = LFS['hrs_away'] / 10
LFS['paid_overtime'] = LFS['paid_overtime'] / 10
LFS['unpaid_overtime'] = LFS['unpaid_overtime'] / 10
LFS['hrs_overtime'] = LFS['hrs_overtime'] / 10

In [52]:
## Formatting categorical variable types 
ordinal_vars = [
    'lf_status', 'age_5y_group', 'education', 'marital_stat', 'work_lasty',
    'job_permenancy', 'estab_size', 'firm_size', 'student_status', 
]

nominal_vars = [
    'province', 'gender', 'multiple_jobh', 'ft_pt_last', 'main_class_worker', 'immigration_stat', 
    'NAICS_21', 'NOC_10', 'NOC_43', 'ft_pt_main', 'union_stat', 'flow_to_unemp' , 'econ_fam_type', 'paid_for_absence'
]
## Converting ordinal variables
for var in ordinal_vars:
    LFS[var] = LFS[var].astype(pd.Int64Dtype())  # Nullable integer type
    LFS[var] = pd.Categorical(LFS[var], ordered=True)

## Converting nominal variables
for var in nominal_vars:
    LFS[var] = LFS[var].astype(pd.Int64Dtype())  # Nullable integer type
    LFS[var] = LFS[var].astype('category')

In [53]:
## Checking dataframe information
print(LFS.info())

## Inspecting the first few rows of the dataset
LFS.head()

<class 'pandas.core.frame.DataFrame'>
Index: 5507987 entries, 2753993 to 2691911
Data columns (total 41 columns):
 #   Column             Dtype
---  ------             -----
 0   REC_NUM            int64
 1   lf_status          category
 2   province           category
 3   age_5y_group       category
 4   gender             category
 5   marital_stat       category
 6   education          category
 7   multiple_jobh      category
 8   work_lasty         category
 9   ft_pt_last         category
 10  main_class_worker  category
 11  immigration_stat   category
 12  NAICS_21           category
 13  NOC_10             category
 14  NOC_43             category
 15  weeks_absent       float64
 16  paid_for_absence   category
 17  usualhrs_main      float64
 18  actualhrs_main     float64
 19  ft_pt_main         category
 20  usualhrs_all       float64
 21  actualhrs_all      float64
 22  hrs_away           float64
 23  paid_overtime      float64
 24  unpaid_overtime    float64
 25  hrs_overtime       float64
 26  current_tenure     float64
 27  prev_tenure        float64
 28  hourly_wage        float64
 29  union_stat         category
 30  job_permenancy     category
 31  estab_size         category
 32  firm_size          category
 33  duration_unemp     float64
 34  flow_to_unemp      category
 35  duration_jobless   float64
 36  student_status     category
 37  econ_fam_type      category
 38  final_wt           int64
 39  REF_DATE           object
 40  Month              category
dtypes: category(24), float64(14), int64(2), object(1)
memory usage: 882.5+ MB
None

         REC_NUM lf_status province age_5y_group gender marital_stat education multiple_jobh work_lasty ft_pt_last main_class_worker immigration_stat NAICS_21 NOC_10 NOC_43  weeks_absent paid_for_absence  usualhrs_main  actualhrs_main ft_pt_main  usualhrs_all  actualhrs_all  hrs_away  paid_overtime  unpaid_overtime  hrs_overtime  current_tenure  prev_tenure  hourly_wage union_stat job_permenancy estab_size firm_size  duration_unemp flow_to_unemp  duration_jobless student_status econ_fam_type  final_wt    REF_DATE Month
2753993    62081         4       24           10      2            2         2           NaN          1          1                 2                3        7      7     31           NaN              NaN            NaN             NaN        NaN           NaN            NaN       NaN            NaN              NaN           NaN             NaN      240.000          NaN        NaN            NaN        NaN       NaN             NaN           NaN             5.000              1             5       345  2023-01-01   Jan
3978222    38908         3       48           10      2            1         2           NaN          2        NaN               NaN                3      NaN    NaN    NaN           NaN              NaN            NaN             NaN        NaN           NaN            NaN       NaN            NaN              NaN           NaN             NaN          NaN          NaN        NaN            NaN        NaN       NaN           8.000             7            23.000              1            11        61  2024-01-01   Jan
3978221    38907         4       35            2      1            6         2           NaN          3        NaN               NaN                3      NaN    NaN    NaN           NaN              NaN            NaN             NaN        NaN           NaN            NaN       NaN            NaN              NaN           NaN             NaN          NaN          NaN        NaN            NaN        NaN       NaN             NaN           NaN               NaN              2             7       268  2024-01-01   Jan
3978220    38906         1       35            8      1            1         4             1        NaN        NaN                 3                3        6      8     35           NaN              NaN         60.000          60.000          1        60.000         60.000       NaN            NaN              NaN           NaN         240.000          NaN          NaN        NaN            NaN        NaN       NaN             NaN           NaN               NaN              1             4       249  2024-01-01   Jan
3978219    38905         1       48            4      1            6         4             1        NaN        NaN                 2                3       20      8     35           NaN              NaN         40.000          40.000          1        40.000         40.000     0.000          0.000            0.000         0.000          33.000          NaN       38.000          3              1          1         1             NaN           NaN               NaN              1             5        81  2024-01-01   Jan

In [54]:
## Exporting the cleaned dataset to a CSV file
LFS.to_csv('Data/LFS/LFS_Cleaned.csv', index=False)

## Job Vacancies

#### Data Loading

In [55]:
## Reading the Job Vacancies CSV file
df = pd.read_csv('Data/Job vacancies, payroll employees, and job vacancy rate by industry sector, monthly, adjusted for seasonality.csv')

## Pivot the dataset to wide format based on the Statistics column
df_wide = df.pivot(index=["REF_DATE", "North American Industry Classification System (NAICS)"], 
                   columns=["Statistics"], values="VALUE").reset_index()

## Inspecting the shape of pivoted dataset
print(f"There are {df_wide.shape[0]} rows, and {df_wide.shape[1]} columns in the pivoted JV dataset")

There are 1071 rows, and 5 columns in the pivoted JV dataset

In [56]:
## Inspecting the first few rows of the pivoted dataset
df_wide.head()

Statistics REF_DATE North American Industry Classification System (NAICS)  Job vacancies  Job vacancy rate  Payroll employees
0           2020-10               Accommodation and food services [72]         48150.000             4.600         992655.000
1           2020-10  Administrative and support, waste management a...         45235.000             5.600         761670.000
2           2020-10    Agriculture, forestry, fishing and hunting [11]         16925.000             6.800         233620.000
3           2020-10            Arts, entertainment and recreation [71]          5935.000             2.700         214675.000
4           2020-10                                  Construction [23]         44195.000             4.200        1000060.000

In [57]:
## Printing the summary information
print("====================Summary information about JV dataset====================")
print(df_wide.info(), "\n") 

## Printing the summary statistics
print("\n====================Summary statistics about JV dataset====================")
df_wide.describe()

====================Summary information about JV dataset====================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1071 entries, 0 to 1070
Data columns (total 5 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   REF_DATE                                               1071 non-null   object
 1   North American Industry Classification System (NAICS)  1071 non-null   object
 2   Job vacancies                                          1062 non-null   float64
 3   Job vacancy rate                                       1062 non-null   float64
 4   Payroll employees                                      1071 non-null   float64
dtypes: float64(3), object(2)
memory usage: 42.0+ KB
None


====================Summary statistics about JV dataset====================

Statistics  Job vacancies  Job vacancy rate  Payroll employees
count            1062.000          1062.000           1071.000
mean            71485.339             4.013        1578931.130
std            159075.253             1.747        3410834.329
min               685.000             0.500         112735.000
25%             11787.500             2.700         292560.000
50%             27282.500             3.800         808025.000
75%             58678.750             5.100        1294655.000
max           1003395.000            13.300       17317010.000

#### Data Cleaning

In [58]:
## Formatting Date columns
df_wide['REF_DATE'] = pd.to_datetime(df_wide['REF_DATE'], format='%Y-%m') 

## Renaming columns for clarity 
df_wide = df_wide.rename(columns={"North American Industry Classification System (NAICS)": "NAICS_21_label", "Job vacancies": "Job Vacancies (#)",
                                 "Job vacancy rate": "Job Vacancy Rate (%)", "Payroll employees": "Payroll Employees (#)"})

## Checking for missing values
print(f"There is {df_wide.isnull().sum()} missing values in JV dataset:\n")
df_wide[df_wide.isnull().any(axis=1)]

There is Statistics
REF_DATE                 0
NAICS_21_label           0
Job Vacancies (#)        9
Job Vacancy Rate (%)     9
Payroll Employees (#)    0
dtype: int64 missing values in JV dataset:

Statistics   REF_DATE                                     NAICS_21_label  Job Vacancies (#)  Job Vacancy Rate (%)  Payroll Employees (#)
19         2020-10-01                                     Utilities [22]                NaN                   NaN             122230.000
187        2021-06-01                                     Utilities [22]                NaN                   NaN             123850.000
334        2022-01-01                                     Utilities [22]                NaN                   NaN             128520.000
342        2022-02-01                         Finance and insurance [52]                NaN                   NaN             784225.000
439        2022-06-01                                     Utilities [22]                NaN                   NaN             129405.000
536        2022-11-01  Mining, quarrying, and oil and gas extraction ...                NaN                   NaN             205700.000
565        2022-12-01                                     Utilities [22]                NaN                   NaN             130780.000
943        2024-06-01                                     Utilities [22]                NaN                   NaN             135020.000
1037       2024-11-01           Information and cultural industries [51]                NaN                   NaN             355840.000

In [59]:
## Interpolating missing values
df_wide["Job Vacancies (#)"] = df_wide.groupby(["REF_DATE", "NAICS_21_label"])["Job Vacancies (#)"].transform(lambda x: x.interpolate(method='linear', limit_direction='both'))
df_wide["Job Vacancy Rate (%)"] = df_wide.groupby(["REF_DATE", "NAICS_21_label"])["Job Vacancy Rate (%)"].transform(lambda x: x.interpolate(method='linear', limit_direction='both'))

##### **Handling Missing Values in the Job Vacancy Dataset**
Missing values in the `Job Vacancies (#)` and `Job Vacancy Rate (%)` columns were identified across different industries and years. Since the dataset spans multiple years (2020-2024) and represents time-series data, a structured imputation approach was used to maintain consistency and preserve labor market trends.

**Time-Series Interpolation (Linear)**
   - Missing values were estimated using **linear interpolation**, and no missing data was at the beginning or end of the dataset.
   - This method ensures that missing values are filled based on the closest valid values before and after the gap.
   - Interpolation was applied separately for each **industry-year group** to maintain industry-specific trends.

##### **Final Outcome**
- The dataset was **fully imputed** using interpolation, ensuring that labor market trends were preserved without introducing artificial bias.
- This method **maintains continuity** in monthly data while reflecting natural fluctuations in job vacancies and job vacancy rates.
- This approach ensures that the **data remains accurate and reliable** for further analysis.

In [60]:
## Define industry mapping to match LFS categories across all years
industry_mapping = {
    'Management of companies and enterprises [55]': 'Business, building and other support services [55-56]',
    'Administrative and support, waste management and remediation services [56]': 'Business, building and other support services [55-56]',
    'Information and cultural industries [51]': 'Information, culture and recreation [51-71]',
    'Arts, entertainment and recreation [71]': 'Information, culture and recreation [51-71]'
}

## Apply mapping to create a new industry column
df_wide["NAICS_combined"] = df_wide["NAICS_21_label"].replace(industry_mapping)
df_wide["NAICS_combined"] = df_wide["NAICS_combined"].fillna(df_wide["NAICS_21_label"])  # Ensure unmapped values remain

## Aggregating data while keeping `Original_NAICS`
JV = df_wide.groupby(["REF_DATE", "NAICS_combined"]).agg({
    "Job Vacancies (#)": "sum",
    "Payroll Employees (#)": "sum",
    "Job Vacancy Rate (%)": lambda x: (x * df_wide.loc[x.index, "Payroll Employees (#)"]).sum() /
                                             df_wide.loc[x.index, "Payroll Employees (#)"].sum()
}).reset_index()

In [61]:
## Extract month name and convert it to an ordered categorical type
df_wide['Month'] = df_wide['REF_DATE'].dt.strftime('%b') 
df_wide['Month'] = pd.Categorical(df_wide['Month'], categories=month_order, ordered=True)

## Extract Year
df_wide["Year"] = df_wide["REF_DATE"].dt.year

In [62]:
## Extracting cleaned JV dataset to a CSV file
JV.to_csv('Data/JV_Cleaned.csv', index=False)

## Consumer Price Index

#### Data Loading

In [63]:
## Reading the Consumer Price Index CSV file
original_CPI = pd.read_csv('Data/Consumer Price Index, monthly, seasonally adjusted.csv')

## Pivot the dataset to wide format based on the Products and Product Groups column
CPI_pivot = original_CPI.pivot(index="REF_DATE", columns="Products and product groups", values="VALUE").reset_index()

## Inspecting the shape of pivoted dataset
print(f"There are {CPI_pivot.shape[0]} rows, and {CPI_pivot.shape[1]} columns in the CPI dataset")

There are 74 rows, and 12 columns in the CPI dataset

In [64]:
## Inspection of the first few rows of the pivoted CPI dataset
CPI_pivot.head()

Products and product groups REF_DATE  Alcoholic beverages, tobacco products and recreational cannabis  All-items  All-items excluding food  All-items excluding food and energy  Clothing and footwear    Food  Health and personal care  Household operations, furnishings and equipment  Recreation, education and reading  Shelter  Transportation
0                            2019-01                                            170.900                  134.300                   131.600                              129.100                 95.000 147.900                   126.000                                          123.800                            115.900  143.000         137.800
1                            2019-02                                            171.000                  134.700                   132.000                              129.500                 95.600 148.500                   126.400                                          123.500                            115.800  143.400         139.100
2                            2019-03                                            170.900                  135.200                   132.500                              129.700                 95.400 149.000                   126.700                                          123.300                            116.000  143.800         140.800
3                            2019-04                                            171.100                  135.600                   132.900                              130.000                 95.500 149.000                   126.800                                          123.500                            116.100  144.100         141.300
4                            2019-05                                            171.300                  136.000                   133.300                              130.400                 95.700 149.500                   127.300                                          123.800                            117.300  144.200         142.400

In [65]:
## Printing the summary information
print("====================Summary information about CPI dataset====================")
print(CPI_pivot.info(), '\n')

## Printing the summary statistics
print("====================Summary statisics about CPI dataset:=======================")
CPI_pivot.describe()

====================Summary information about CPI dataset====================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 12 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   REF_DATE                                                         74 non-null     object
 1   Alcoholic beverages, tobacco products and recreational cannabis  74 non-null     float64
 2   All-items                                                        74 non-null     float64
 3   All-items excluding food                                         74 non-null     float64
 4   All-items excluding food and energy                              74 non-null     float64
 5   Clothing and footwear                                            74 non-null     float64
 6   Food                                                             74 non-null     float64
 7   Health and personal care                                         74 non-null     float64
 8   Household operations, furnishings and equipment                  74 non-null     float64
 9   Recreation, education and reading                                74 non-null     float64
 10  Shelter                                                          74 non-null     float64
 11  Transportation                                                   74 non-null     float64
dtypes: float64(11), object(1)
memory usage: 7.1+ KB
None

====================Summary statisics about CPI dataset:=======================

Products and product groups  Alcoholic beverages, tobacco products and recreational cannabis  All-items  All-items excluding food  All-items excluding food and energy  Clothing and footwear    Food  Health and personal care  Household operations, furnishings and equipment  Recreation, education and reading  Shelter  Transportation
count                                                                   74.000                   74.000                    74.000                               74.000                 74.000  74.000                    74.000                                           74.000                             74.000   74.000          74.000
mean                                                                   181.332                  147.707                   143.858                              140.004                 94.904 168.315                   137.628                                          127.792                            121.428  161.073         157.554
std                                                                      9.752                   10.086                     9.183                                8.109                  1.598  15.515                     8.884                                            3.728                              4.905   14.449          13.381
min                                                                    170.800                  134.300                   131.600                              129.100                 90.500 147.900                   126.000                                          123.200                            114.400  143.000         136.200
25%                                                                    171.950                  137.350                   134.225                              131.925                 93.700 154.050                   129.025                                          123.825                            116.800  146.725         142.875
50%                                                                    178.400                  146.800                   143.350                              138.450                 94.850 164.350                   134.750                                          127.400                            121.450  158.100         160.450
75%                                                                    191.375                  157.950                   153.100                              147.850                 96.050 185.150                   146.750                                          131.175                            126.350  173.650         170.375
max                                                                    198.500                  163.700                   158.700                              153.900                 98.700 191.500                   152.400                                          133.500                            130.400  186.700         175.700

#### Data Cleaning

In [66]:
## Formatting Date columns
CPI_pivot["REF_DATE"] = pd.to_datetime(CPI_pivot["REF_DATE"], format='%Y-%m')

## Extract month name and convert it to an ordered categorical type
CPI_pivot['Month'] = CPI_pivot['REF_DATE'].dt.strftime('%b') 
CPI_pivot['Month'] = pd.Categorical(CPI_pivot['Month'], categories=month_order, ordered=True)

## Extract Year
CPI_pivot["Year"] = CPI_pivot["REF_DATE"].dt.year 

## Sorting by date
CPI_pivot = CPI_pivot.sort_values(by="REF_DATE")

In [67]:
## Extracting  All-items column and creating a new dataframe copy
CPI = CPI_pivot[['REF_DATE', 'Month', 'Year', "All-items"]]
CPI = CPI.copy()

## Extracting cleaned CPI dataset to a CSV file
CPI.to_csv('Data/CPI_Cleaned.csv', index=False)

## Data Exploration

In [69]:
## Creating basic exploratory data analysis reports

LFS_report = sv.analyze(LFS)
LFS_report.show_html('LFS_EDA_Report.html')

JV_report = sv.analyze(JV)
JV_report.show_html('JV_EDA_Report.html')

CPI_report = sv.analyze(CPI)
CPI_report.show_html('CPI_EDA_Report.html')

                                             |          | [  0%]   00:00 -> (? left)

Report LFS_EDA_Report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.
---
WARNING: one or more correlations had an edge-case/error and a 1.0 correlation was assigned
(likely due to only having a single row, containing non-NaN values for both correlated features)
Affected correlations:['weeks_absent/actualhrs_main', 'weeks_absent/actualhrs_all', 'actualhrs_main/weeks_absent', 'actualhrs_all/weeks_absent']

                                             |          | [  0%]   00:00 -> (? left)

Report JV_EDA_Report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

                                             |          | [  0%]   00:00 -> (? left)

Report CPI_EDA_Report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.